# Generated by Django 6.0.2 on 2026-03-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_user_pass_hash_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1200000$mXEzDP7xhxv6EJMnSSyxdR$qfwu6AYqwI80EJ9Nzodm4KkLs2MbG4B1TyCJeC0x/Mc=', max_length=255),
        ),
    ]
