# Generated by Django 6.0.2 on 2026-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_image_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1200000$K6zf4FIREPCdS3Nr7sqgVq$2pQCn70YFRFzQ8PyR5lz9q2gAf9MYhjdvNBrsL2cqd8=', max_length=255),
        ),
    ]
