# Generated by Django 6.0.2 on 2026-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_image_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1200000$pcN19n3zklY0hMM37CmATi$7a3zJLyOzmCPCbzY2PGPXjC6ajvz/uLmELG2B4brBP0=', max_length=255),
        ),
    ]
